<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<c:set value="${pageContext.request.contextPath}" var="rootPath" />

<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>또가자</title>

</head>
<%@ include file="/WEB-INF/views/dosung/head.jsp"%>
<body>
	<%@ include file="/WEB-INF/views/dosung/header.jsp"%>

	<div class="d-main">
		<div class="hshshs">
			<a class="hshsa" href="${rootPath}/api/map" class="hs_btns">&#43; 지도</a>
		</div>

		<div class="d-map">
			<!-- Image Map Generated by http://www.image-map.net/ -->
			<img src="${rootPath}/static/images/busan_background.png"
				usemap="#busan" id="map-img">
			<map name="busan">
				<area target="_blank" alt="강서구" title="강서구"
					onclick="dosungPower(event)"
					coords="201,198,132,225,117,224,86,229,80,243,98,283,66,286,42,291,10,296,36,325,56,352,52,368,12,419,14,462,43,502,73,421,119,416,131,390,132,356,150,348,167,293,170,257,186,232"
					shape="poly">
				<area target="_blank" alt="사상구" title="사상구"
					onclick="dosungPower(event)"
					coords="197,245,179,251,172,280,166,329,181,339,205,335,211,308,223,305,226,296,221,281,226,256,221,250"
					shape="poly">
				<area target="_blank" alt="사하구" title="사하구"
					onclick="dosungPower(event)"
					coords="173,340,160,339,151,353,152,376,163,358,170,361,164,379,173,418,181,428,189,426,184,414,195,408,209,421,204,404,206,383,216,371,222,365,217,360,217,351,210,342"
					shape="poly">
				<area target="_blank" alt="서구" title="서구"
					onclick="dosungPower(event)"
					coords="221,316,214,315,215,331,214,342,223,353,228,370,226,384,236,386,238,371,230,355,231,341,230,326,234,320"
					shape="poly">
				<area target="_blank" alt="영도구" title="영도구"
					onclick="dosungPower(event)"
					coords="269,362,253,367,246,377,254,385,262,385,277,400,286,405,298,416,307,409,293,395,295,388,289,375,281,367"
					shape="poly">
				<area target="_blank" alt="중구" title="중구"
					onclick="dosungPower(event)"
					coords="240,341,250,343,255,352,248,364,241,364,234,358,234,348"
					shape="poly">
				<area target="_blank" alt="동구" title="동구"
					onclick="dosungPower(event)"
					coords="254,303,244,317,237,324,236,340,254,340,261,332,268,328,275,320,273,311"
					shape="poly">
				<area target="_blank" alt="남구" title="남구"
					onclick="dosungPower(event)"
					coords="304,286,293,296,277,301,278,316,282,331,282,346,301,344,309,359,319,357,333,358,338,348,338,330,321,316,311,308"
					shape="poly">
				<area target="_blank" alt="수영구" title="수영구"
					onclick="dosungPower(event)"
					coords="309,264,304,282,314,304,325,311,325,295,341,289,333,278,327,269"
					shape="poly">
				<area target="_blank" alt="해운대구" title="해운대구"
					onclick="dosungPower(event)"
					coords="356,179,343,200,327,206,334,216,325,224,331,240,328,265,346,284,369,291,375,284,400,285,410,259,418,254,409,240,392,249,390,238,369,232,366,217,375,210,367,198"
					shape="poly">
				<area target="_blank" alt="부산진구" title="부산진구"
					onclick="dosungPower(event)"
					coords="250,241,231,248,225,273,231,298,228,315,242,314,250,302,272,309,281,296,289,290,286,277,285,267,272,267,261,258"
					shape="poly">
				<area target="_blank" alt="연제구" title="연제구"
					onclick="dosungPower(event)"
					coords="259,245,263,254,276,260,288,261,290,280,302,281,303,266,310,259,322,261,318,249,302,247,287,237,274,247"
					shape="poly">
				<area target="_blank" alt="동래구" title="동래구"
					onclick="dosungPower(event)"
					coords="283,205,267,212,264,228,252,238,272,243,282,234,297,241,315,244,327,253,323,228,313,225,299,221"
					shape="poly">
				<area target="_blank" alt="북구" title="북구"
					onclick="dosungPower(event)"
					coords="233,145,212,166,205,192,195,231,205,241,223,245,242,238,254,231,265,208,255,201,255,187,250,173,243,163,250,148"
					shape="poly">
				<area target="_blank" alt="금정구" title="금정구"
					onclick="dosungPower(event)"
					coords="265,120,248,163,260,183,260,199,272,205,286,202,302,214,318,219,327,213,323,202,339,199,346,176,328,154,329,142,331,126,334,121,310,106,298,111,282,129"
					shape="poly">
				<area target="_blank" alt="기장군" title="기장군"
					onclick="dosungPower(event)"
					coords="341,40,345,64,319,109,344,122,337,132,339,143,331,155,351,173,367,186,376,208,381,217,370,225,378,236,391,237,411,239,431,243,429,223,439,199,451,196,460,173,442,169,443,156,454,154,464,146,464,95,486,78,503,84,504,68,482,56,487,43,469,8,426,17,406,10,400,29,395,45,372,48"
					shape="poly">
			</map>


		</div>
		<div class="d-content"></div>
	</div>
</body>

</html>